version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html

    depends_on:
      - tomcat

  tomcat:
    build:
      context: .
      dockerfile: Dockerfile-java
    ports:
      - "8585:8080"
    volumes:
      - ./server-java/lib/mysql-connector-java-8.0.28.jar:/usr/local/tomcat/lib/mysql-connector-java-8.0.28.jar
      - ./server-java/lib/gson-2.10.1.jar:/usr/local/tomcat/lib/gson-2.10.1.jar
      - ./server-java/lib/jakarta.servlet-api-5.0.0.jar:/usr/local/tomcat/lib/jakarta.servlet-api-5.0.0.jar
      - ./server-java/web/WEB-INF:/usr/local/tomcat/webapps/ROOT/WEB-INF

  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: mydatabase
    volumes:
      - db-data:/var/lib/mysql
      #- ./sql-scripts/:/docker-entrypoint-initdb.d/
      #- ./my.cnf:/etc/mysql/conf.d

  phpmyadmin:
    build:
      context: .
      dockerfile: Dockerfile-phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db-data:


